url: https://swcdn.apple.com/content/downloads/63/47/001-39934/955xl2euy0wb5j2z4oddbbd39ln1sthedn/AppleApplicationSupport64.msi
automatic_install: false
self_service: false
categories: []

# Categories are currently limited to Browsers, Communication, Developer tools, and Productivity.
# This is a minimum version of this file. All configurable parameters can be seen at https://fleetdm.com/docs/rest-api/rest-api#parameters139
