url: https://dl.dell.com/FOLDER12902766M/1/Dell-Command-Configure-Application_MD8CJ_WIN64_5.2.0.9_A00.EXE
automatic_install: false
self_service: false
categories: []
install_script: '# TODO: Add install script for this EXE'
uninstall_script: '# TODO: Add uninstall script for this EXE'

# Categories are currently limited to Browsers, Communication, Developer tools, and Productivity.
# This is a minimum version of this file. All configurable parameters can be seen at https://fleetdm.com/docs/rest-api/rest-api#parameters139
# Note: Any exe requires an install script and uninstall script to be defined
