url: https://javadl.oracle.com/webapps/download/GetFile/1.8.0_431-b10/0d8f12bc927a4e2c9f8568ca567db4ee/windows-i586/jre-8u431-windows-x64.exe
automatic_install: false
self_service: false
categories: []
install_script: '# TODO: Add install script for this EXE'
uninstall_script: '# TODO: Add uninstall script for this EXE'

# Categories are currently limited to Browsers, Communication, Developer tools, and Productivity.
# This is a minimum version of this file. All configurable parameters can be seen at https://fleetdm.com/docs/rest-api/rest-api#parameters139
# Note: Any exe requires an install script and uninstall script to be defined
