url: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases/download/v5.7.3/AdvancedSettings-5.7.3-Installer.exe
automatic_install: false
self_service: false
categories: []
install_script: '# TODO: Add install script for this EXE'
uninstall_script: '# TODO: Add uninstall script for this EXE'

# Categories are currently limited to Browsers, Communication, Developer tools, and Productivity.
# This is a minimum version of this file. All configurable parameters can be seen at https://fleetdm.com/docs/rest-api/rest-api#parameters139
# Note: Any exe requires an install script and uninstall script to be defined
